apiVersion: v1 
kind: Pod 
metadata: 
  name: nw1-pod 
  annotations: 
    ovn.kubernetes.io/logical_switch: nw1 
spec: 
  containers: 
    - name: nw1-container 
      image: "alpine:3.17" 
      command: ["ping"] 
      args: ["8.8.8.8"] 
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: nw10-pod 
  annotations: 
    ovn.kubernetes.io/logical_switch: nw10 
spec: 
  containers: 
    - name: nw10-container 
      image: "alpine:3.17" 
      command: ["ping"] 
      args: ["8.8.8.8"] 