apiVersion: v1
kind: Pod
metadata:
  annotations:
    ovn.kubernetes.io/logical_switch: nw1
    ovn.kubernetes.io/ip_address: 10.18.1.10
  labels:
    app: fl-deployment-server
  name: fl-deployment-server-54647cd88b-2r9vq
  namespace: default
spec:
  nodeName: perf-server
  containers:
  - args:
    - sleep infinity; 
    command:
    - /bin/sh
    - -c
    image: "alpine:3.17" 
    imagePullPolicy: IfNotPresent
    name: fl-server
    ports:
    - containerPort: 8080
      protocol: TCP